name: Mixin

web: "[http://sharedhat.com](http://sharedhat.com)"

description: "It builds in the class and crowding and a variety of Mixin classes are offered."

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://holyshared.github.com/Mixin/license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/Class.Attachment.js"

author: Noritaka Horio

category: Utilities

tags: [utils, mixin, class]

current: 1.0

#docs: http://holyshared.github.com/Mixin/docs

demo: http://holyshared.github.com/Mixin/